### ISSUE TITLE
Add option to overwrite puppeteer browser options

### ISSUE THREAD

**Issue by smeijer** [ashubham/webshot-factory#1]
It would be nice if we could overwrite some puppeteer settings. For example, I currently need to pass the executablePath to puppeteer.

Because of this requirement, I'm unable to use this library, and need to control puppeteer myself.

Having this possibility, would be awesome.

**Comment by sagar1993** [comment]
An option to pass executablePath has been added https://github.com/ashubham/webshot-factory/pull/5

**Comment by sagar1993** [comment]
Alternately we can set the path in the environment variable PUPPETEER_EXECUTABLE_PATH
